/**
 * Frozen content for the old (v1) site at /old.
 * Copied from the live site on 2026-10-10 so the old site no longer reads anything
 * the admin dashboard can change. Images were saved to public/old-site/.
 */
import type { Course, SuccessStory } from "@server/database/schema";

/** Site Content values the old site showed; anything missing falls back to the hook's defaults. */
export const OLD_SITE_SETTINGS: Record<string, string> = {
  "about_description": "Fluent Learner is one of Bangladesh's leading IELTS platforms dedicated to IELTS VIP One-to-One preparation. We specialize in delivering result-oriented, personalized IELTS courses to help students and professionals achieve their target band scores—no matter where they are.\n\nWith a focus on one-to-one mentorship, expert guidance, and strategic learning, our programs are designed to make IELTS success accessible for everyone. Whether you're just starting or aiming for a Band 8+, Fluent Learner offers flexible, online-based solutions tailored to your needs.\n\n100% VIP Success | 8.0+ Score-Focused | | We have 10000+ IELTS Scorer till March 2026\n\nAt Fluent Learner, we don’t just teach English—we build your future.\n\n\n\"Your dream is the blueprint for your future. Dream without limits, because greatness is never built on small plans. Success stories aren't written by mere dreamers, but by the architects of ambition—those who have the courage to build their vision into reality.\"\n\n- Quote by: Zahid Sir",
  "about_title": " 100% VIP Success | 8.0+ Score-Focused | We have 10000+ IELTS Scorer till March 2026",
  "founder_bio": "Leadership Expert & Coach | IELTS and Spoken Expert | Speaker | Social Activist\n\nAs a Founder and CEO of FluentLearner, I bring over 15 years of leadership experience in national and international organizations, empowering youth and professionals to achieve excellence. Through FluentLearner, I am committed to fostering English proficiency, leadership skills, and personal growth to build a sustainable and thriving society.",
  "founder_name": "Aditow Zahid",
  "founder_photo": "/old-site/JAMx89dSKoL2hJ-tYDyeS.jpeg",
  "founder_title": "CEO & Founder, Fluent Learner IELTS",
  "hero_cta_text": "Enroll Now",
  "hero_image": "/old-site/sdF95UCLwtdeUZTv873tU.jpeg",
  "stat_avg_band": "7.5+",
  "stat_facebook_followers": "77k",
  "stat_success_rate": "98.95%",
  "stat_total_scorers": "10,000+"
};

export const OLD_COURSES = [
  {
    "id": 3,
    "name": "IELTS VIP (Online Private Batch)",
    "nameEn": "IELTS VIP : 30+ Live Class",
    "shortDescription": "30+ Live Class  Band 8.0+ Target 1-on-1 Mentorship with Zahid Sir 1-on-1 Feedback Sessions All Classes taken by Zoom App Record Class Access Student Portal Access Unlimited Cambridge & Official IELTS Mock Tests  5 AI-Based Special Mock Tests Fee Resources & Materials Problem-Solving sessions Speaking Club Access 1 Year Access",
    "description": "30+ Live Class \nBand 8.0+ Target\n1-on-1 Mentorship with Zahid Sir\n1-on-1 Feedback Sessions\nRecord Class Access\nStudent Portal Access\nUnlimited Cambridge Mock Tests\n15 AI-Based Special Mock Tests\nFee Resources & Materials\nProblem-Solving sessions\nSpeaking Club Access\n1 Year Access",
    "imageUrl": "/old-site/O38OZxfolpOTLkt6-1PeH.jpeg",
    "duration": "1.5 Month  (Weekly 4/5 Classes)",
    "originalPrice": "Course Fee ৳,13,000",
    "price": "৳8,500 ",
    "badge": "Most Popular",
    "badgeColor": "bg-red-500",
    "category": "ielts",
    "level": "all",
    "features": [
      "30+ Live Class ",
      "Band 8.0+ Target",
      "1-on-1 Mentorship with Zahid Sir",
      "1-on-1 Feedback Sessions",
      "All Classes taken by Zoom App",
      "Record Class Access",
      "Student Portal Access",
      "Unlimited Cambridge & Official IELTS Mock Tests",
      "15 AI-Based Special Mock Tests",
      "Fee Resources & Materials",
      "Problem-Solving sessions",
      "Speaking Club Access",
      "1 Year Access"
    ],
    "learningOutcomes": [
      "30+ Live Class ",
      "Band 8.0+ Target",
      "1-on-1 Mentorship with Zahid Sir",
      "1-on-1 Feedback Sessions",
      "All Classes taken by Zoom App",
      "Record Class Access",
      "Student Portal Access",
      "Unlimited Cambridge & Official IELTS Mock Tests",
      "15 AI-Based Special Mock Tests",
      "Fee Resources & Materials",
      "Problem-Solving sessions",
      "Speaking Club Access",
      "1 Year Access"
    ],
    "schedule": "Weekly 4/5 Live Class",
    "maxStudents": null,
    "enrolledCount": 7,
    "fullDescription": "",
    "curriculum": [],
    "targetAudience": "",
    "instructorName": "",
    "instructorBio": "",
    "instructorPhoto": "",
    "courseFaq": [],
    "videoUrl": "",
    "slug": "ielts-vip-course",
    "enrollMessage": "আমি IELTS VIP Batch-এ ভর্তি হতে চাই। বিস্তারিত জানতে চাই।",
    "sortOrder": 1,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-05-14T10:03:24.000Z",
    "updatedAt": "2026-09-07T19:21:13.000Z"
  },
  {
    "id": 7,
    "name": "Basic to IELTS (Online Private Batch)",
    "nameEn": "Basic to IELTS VIP",
    "shortDescription": "40+ Live Class (Band 8.0+ Target) 1-on-1 Mentorship with Zahid Sir 1-on-1 Feedback Sessions Extra Care and Repeat Class Speaking Club Access 10 Full AI Mock Test Fee Resources & Materials Updated Record Class Problem Solving sessions 1 Year Access",
    "description": "40+ Live Class \nBand 8.0+ Target\n1-on-1 Mentorship with Zahid Sir\n1-on-1 Feedback Sessions\nAll Classes taken by Zoom App\nRecord Class Access\nStudent Portal Access\nUnlimited Cambridge Mock Tests\n20 AI-Based Special Mock Tests\nFee Resources & Materials\nProblem-Solving sessions\nSpeaking Club Access\n1 Year Access",
    "imageUrl": "/old-site/YhBtIWizBabdHs_68E67m.jpeg",
    "duration": "2.5 Month  (Weekly 3/4 Classes)",
    "originalPrice": "Course Fee 16,000",
    "price": "৳10,500",
    "badge": "Most Popular",
    "badgeColor": "bg-blue-500",
    "category": "ielts",
    "level": "all",
    "features": [
      "40+ Live Class ",
      "Band 8.0+ Target",
      "1-on-1 Mentorship with Zahid Sir",
      "1-on-1 Feedback Sessions",
      "All Classes taken by Zoom App",
      "Record Class Access",
      "Student Portal Access",
      "Unlimited Cambridge Mock Tests",
      "20 AI-Based Special Mock Tests",
      "Fee Resources & Materials",
      "Problem-Solving sessions",
      "Speaking Club Access",
      "1 Year Access"
    ],
    "learningOutcomes": [
      "40+ Live Class ",
      "Band 8.0+ Target",
      "1-on-1 Mentorship with Zahid Sir",
      "1-on-1 Feedback Sessions",
      "All Classes taken by Zoom App",
      "Record Class Access",
      "Student Portal Access",
      "Unlimited Cambridge Mock Tests",
      "20 AI-Based Special Mock Tests",
      "Fee Resources & Materials",
      "Problem-Solving sessions",
      "Speaking Club Access",
      "1 Year Access"
    ],
    "schedule": "Weekly 3/4 Live Class",
    "maxStudents": null,
    "enrolledCount": null,
    "fullDescription": "",
    "curriculum": [],
    "targetAudience": "",
    "instructorName": "Aditow Zahid",
    "instructorBio": "Leadership Expert & Coach | IELTS and Spoken Expert | Speaker | Social Activist\n\nAs a Founder and CEO of FluentLearner, I bring over 15 years of leadership experience in national and international organizations, empowering youth and professionals to achieve excellence. Through FluentLearner, I am committed to fostering English proficiency, leadership skills, and personal growth to build a sustainable and thriving society.",
    "instructorPhoto": "/old-site/JAMx89dSKoL2hJ-tYDyeS.jpeg",
    "courseFaq": [],
    "videoUrl": "",
    "slug": "basic-to-ielts",
    "enrollMessage": "আমি Basic to IELTS-এ ভর্তি হতে চাই। বিস্তারিত জানতে চাই।",
    "sortOrder": 2,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-05-18T20:37:13.000Z",
    "updatedAt": "2026-10-09T16:35:14.000Z"
  },
  {
    "id": 9,
    "name": "IELTS Speaking Premium (Online Private Batch)",
    "nameEn": "IELTS Speaking (One-to-One)",
    "shortDescription": "Band 8.0+ Focused  (Weekly 3/4 Live Class)",
    "description": "Band 8.0+ Focused\nWeekly 3/4 Live Class\n16+ Classes\nOne-to-One Mock Tests\nOne-to-One Mentorship\nSuccess within a week",
    "imageUrl": "/old-site/mgzxH8IgLcEqpEbxyEcsY.jpg",
    "duration": "1 Month+ (Weekly 3/4 Live Class)",
    "originalPrice": "৳ 5,000",
    "price": "৳ 3,000",
    "badge": "Most Popular",
    "badgeColor": "bg-red-500",
    "category": "ielts",
    "level": "all",
    "features": [
      "Band 8.0+ Focused",
      "Weekly 3/4 Live Class",
      "16+ Classes",
      "One-to-One Mock Tests",
      "One-to-One Mentorship",
      "Success within a week"
    ],
    "learningOutcomes": [
      "IELTS Speaking Part 1 ",
      "IELTS Speaking Part 2",
      "IELTS Speaking Part 3",
      "Advanced Grammar",
      "Vocabulary",
      "Fluency",
      "Pronunciation",
      "Advanced Sentence Structure"
    ],
    "schedule": "Weekly 3/4 Live Class",
    "maxStudents": null,
    "enrolledCount": null,
    "fullDescription": "",
    "curriculum": [],
    "targetAudience": "",
    "instructorName": "",
    "instructorBio": "",
    "instructorPhoto": "",
    "courseFaq": [],
    "videoUrl": "",
    "slug": "ielts-speaking-one-to-one",
    "enrollMessage": "I want to enroll IELTS Speaking One-to-One Course",
    "sortOrder": 3,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-05-31T13:37:52.000Z",
    "updatedAt": "2026-09-07T19:07:04.000Z"
  }
] as unknown as Course[];

const FEATURED_COURSE_IDS = [3, 7, 9];
export const OLD_FEATURED_COURSES = OLD_COURSES.filter(course =>
  FEATURED_COURSE_IDS.includes(course.id)
);

export const OLD_STORIES = [
  {
    "id": 14,
    "studentName": "Arafat Hossain",
    "imageUrl": "/old-site/wjlMDtn_7yI1JDwSOdYoV.jpeg",
    "thumbnailUrl": "",
    "bandScore": "6.5",
    "courseName": "IELTS VIP Private Batch + UK Student Visa",
    "testimonial": "",
    "category": "visa-success",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-25T13:38:27.000Z",
    "updatedAt": "2026-07-25T13:38:27.000Z"
  },
  {
    "id": 13,
    "studentName": "Lailun Tonny",
    "imageUrl": "/old-site/OwfLv2X5Rrs5ergRYlYyI.jpg",
    "thumbnailUrl": "",
    "bandScore": "7.5",
    "courseName": "IELTS VIP",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:10:08.000Z",
    "updatedAt": "2026-07-25T13:43:26.000Z"
  },
  {
    "id": 12,
    "studentName": "Mujahid Bijoy",
    "imageUrl": "/old-site/wh7e8-6thnW2HRpvzmIwm.jpg",
    "thumbnailUrl": "",
    "bandScore": "Band 8.0",
    "courseName": "IELTS VIP ",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:09:34.000Z",
    "updatedAt": "2026-07-25T13:43:20.000Z"
  },
  {
    "id": 11,
    "studentName": "SAjal Chakladar",
    "imageUrl": "/old-site/1d7GodRZ-R-iomtI0xDbB.jpg",
    "thumbnailUrl": "",
    "bandScore": "8.0",
    "courseName": "",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:08:56.000Z",
    "updatedAt": "2026-07-19T08:08:56.000Z"
  },
  {
    "id": 10,
    "studentName": "DR Milon Chowdhury",
    "imageUrl": "/old-site/jykeKCuUMSPN45q3eTs4A.jpg",
    "thumbnailUrl": "",
    "bandScore": "8.0",
    "courseName": "IELTS VIP",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:08:32.000Z",
    "updatedAt": "2026-07-19T08:08:32.000Z"
  },
  {
    "id": 9,
    "studentName": "Mohona Akter",
    "imageUrl": "/old-site/nhNhijLuiaSwQt7LU5oVI.jpg",
    "thumbnailUrl": "",
    "bandScore": "7.0",
    "courseName": "IELTS VIP",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:07:13.000Z",
    "updatedAt": "2026-07-19T08:07:13.000Z"
  },
  {
    "id": 8,
    "studentName": "Je",
    "imageUrl": "/old-site/DeicSRlG_yBBFZC9lRghu.jpg",
    "thumbnailUrl": "",
    "bandScore": "",
    "courseName": "IELTS VIP Online Private Batch",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:06:42.000Z",
    "updatedAt": "2026-07-19T08:06:42.000Z"
  },
  {
    "id": 7,
    "studentName": "Golam Imran",
    "imageUrl": "/old-site/pUYFIYZkuaNWaB2em_cAW.jpg",
    "thumbnailUrl": "",
    "bandScore": "",
    "courseName": "IELTS VIP",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:05:58.000Z",
    "updatedAt": "2026-07-19T08:05:58.000Z"
  },
  {
    "id": 6,
    "studentName": "Dr Al Amin Kabir",
    "imageUrl": "/old-site/E4ZrJ7-ofgi0f6C9W19BQ.jpg",
    "thumbnailUrl": "",
    "bandScore": "",
    "courseName": "IELTS VIP Course",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:05:22.000Z",
    "updatedAt": "2026-07-19T08:05:22.000Z"
  },
  {
    "id": 5,
    "studentName": "Supriya Battu",
    "imageUrl": "/old-site/4k2RLLGdWdANI24FkT9Og.jpg",
    "thumbnailUrl": "",
    "bandScore": "7.5",
    "courseName": "IELTS VIP ",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:04:48.000Z",
    "updatedAt": "2026-07-19T08:04:48.000Z"
  },
  {
    "id": 4,
    "studentName": "Ayem Samad",
    "imageUrl": "/old-site/ccSQzUuhT-FMktfjPqfU6.jpg",
    "thumbnailUrl": "",
    "bandScore": "7.5",
    "courseName": "",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:04:15.000Z",
    "updatedAt": "2026-07-19T08:04:15.000Z"
  },
  {
    "id": 3,
    "studentName": "Asia Kimi",
    "imageUrl": "/old-site/4vWFqoCINqNoO0zOGfsL0.jpeg",
    "thumbnailUrl": "",
    "bandScore": "7.0",
    "courseName": "IELTS VIP",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": true,
    "createdAt": "2026-07-19T08:03:46.000Z",
    "updatedAt": "2026-07-19T08:03:46.000Z"
  },
  {
    "id": 2,
    "studentName": "Nazmul",
    "imageUrl": "/old-site/ETgV34vlC4GuxgWEKcssO.jpeg",
    "thumbnailUrl": "",
    "bandScore": "7.5",
    "courseName": "VIP",
    "testimonial": "",
    "category": "ielts-score",
    "achievementDate": "",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": false,
    "createdAt": "2026-07-04T09:40:20.000Z",
    "updatedAt": "2026-07-04T09:40:20.000Z"
  },
  {
    "id": 1,
    "studentName": "Mohim Alam ",
    "imageUrl": "/old-site/V6hX4cgzlONV6EHv7Ufgo.jpeg",
    "thumbnailUrl": "",
    "bandScore": "",
    "courseName": "IELTS VIP + German VIsa",
    "testimonial": "",
    "category": "visa-success",
    "achievementDate": "March 2026",
    "sortOrder": 0,
    "isActive": true,
    "isFeatured": false,
    "createdAt": "2026-05-26T12:01:58.000Z",
    "updatedAt": "2026-05-26T12:01:58.000Z"
  }
] as unknown as SuccessStory[];

const FEATURED_STORY_IDS = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14];
export const OLD_FEATURED_STORIES = OLD_STORIES.filter(story =>
  FEATURED_STORY_IDS.includes(story.id)
);

/** A course by slug or numeric id, the way the course detail page looks it up. */
export function findOldCourse(slugOrId: string): Course | undefined {
  return /^\d+$/.test(slugOrId)
    ? OLD_COURSES.find(course => course.id === Number(slugOrId))
    : OLD_COURSES.find(course => course.slug === slugOrId);
}
