CREATE TABLE `courses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`shortDescription` text,
	`description` text,
	`imageUrl` text,
	`duration` varchar(100),
	`originalPrice` varchar(50),
	`price` varchar(50),
	`badge` varchar(50),
	`badgeColor` varchar(50),
	`category` enum('ielts','spoken','grammar','study-abroad','other') NOT NULL DEFAULT 'ielts',
	`level` enum('beginner','intermediate','advanced','all') NOT NULL DEFAULT 'all',
	`features` json,
	`learningOutcomes` json,
	`schedule` text,
	`maxStudents` int,
	`enrolledCount` int DEFAULT 0,
	`enrollMessage` text,
	`sortOrder` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `courses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `success_stories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentName` varchar(255) NOT NULL,
	`imageUrl` text NOT NULL,
	`thumbnailUrl` text,
	`bandScore` varchar(10),
	`courseName` varchar(255),
	`testimonial` text,
	`storyCategory` enum('ielts-score','visa-success','university-admission','spoken-english','other') NOT NULL DEFAULT 'ielts-score',
	`achievementDate` varchar(50),
	`sortOrder` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `success_stories_id` PRIMARY KEY(`id`)
);
